In [2]:
import torch
import torch.nn as nn

# Batch Norm

In [23]:
x = torch.Tensor([
    [[
        [3,4],
        [5,6]
    ]]
    ,
    [[
        [1,2],
        [3,4]
    ]]
])
print(x)
print(x.shape)
print()


x = nn.BatchNorm2d(1)(x)
print(x)
print(x.shape)

tensor([[[[3., 4.],
          [5., 6.]]],


        [[[1., 2.],
          [3., 4.]]]])
torch.Size([2, 1, 2, 2])

tensor([[[[-0.3333,  0.3333],
          [ 1.0000,  1.6667]]],


        [[[-1.6667, -1.0000],
          [-0.3333,  0.3333]]]], grad_fn=<NativeBatchNormBackward0>)
torch.Size([2, 1, 2, 2])


# Layer Norm

In [21]:
x = torch.Tensor([
    [5,6,7],
    [3,4,5]
])
print(x)
print(x.shape)
print()


x = nn.LayerNorm(x.shape[-1])(x)
print(x)
print(x.shape)


tensor([[5., 6., 7.],
        [3., 4., 5.]])
torch.Size([2, 3])

tensor([[-1.2247e+00,  2.3842e-07,  1.2247e+00],
        [-1.2247e+00,  0.0000e+00,  1.2247e+00]],
       grad_fn=<NativeLayerNormBackward0>)
torch.Size([2, 3])
