## swin transformer paper (https://arxiv.org/pdf/2103.14030.pdf)

In [1]:
import torch
import timm

In [2]:
model = timm.create_model("swin_base_patch4_window7_224")
print('the number of model parameters: {:,}'.format(sum([p.data.nelement() for p in model.parameters()])))
print(model)

/home/ljj0512/.conda/envs/torch/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


the number of model parameters: 87,768,224
SwinTransformer(
  (patch_embed): PatchEmbed(
    (proj): Conv2d(3, 128, kernel_size=(4, 4), stride=(4, 4))
    (norm): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
  )
  (pos_drop): Dropout(p=0.0, inplace=False)
  (layers): Sequential(
    (0): BasicLayer(
      (blocks): Sequential(
        (0): SwinTransformerBlock(
          (norm1): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
          (attn): WindowAttention(
            (qkv): Linear(in_features=128, out_features=384, bias=True)
            (attn_drop): Dropout(p=0.0, inplace=False)
            (proj): Linear(in_features=128, out_features=128, bias=True)
            (proj_drop): Dropout(p=0.0, inplace=False)
            (softmax): Softmax(dim=-1)
          )
          (drop_path): Identity()
          (norm2): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
          (mlp): Mlp(
            (fc1): Linear(in_features=128, out_features=512, bias=True)
            

In [3]:
model = timm.create_model("swin_base_patch4_window12_384")
print('the number of model parameters: {:,}'.format(sum([p.data.nelement() for p in model.parameters()])))
# print(model)

the number of model parameters: 87,903,584


In [4]:
model = timm.create_model("swin_base_patch4_window7_224")

inputs = torch.randn((2,3,224,224))
# print(model(inputs).shape)

inputs = model.patch_embed(inputs)
print(inputs.shape) # (B, 3136, 128)

inputs = model.layers[0].blocks[0](inputs)
print(inputs.shape) # (B, 3136, 128)

torch.Size([2, 3136, 128])
torch.Size([2, 3136, 128])


In [5]:
# (56, 56)  <==  actual fed image size {patch size = 4  -->  inputs image H, W = 224  -->  224/4 = 56}
print(model.patch_embed.grid_size)
print()

# The input image resolution is gradually decreasing!!!!
for i in range(len(model.layers)):
    print(model.layers[i].input_resolution)

(56, 56)

(56, 56)
(28, 28)
(14, 14)
(7, 7)


In [6]:
for i, layer in enumerate(model.layers):
    if i+1 < len(model.layers):
        print("downsample",layer.downsample.input_resolution)
    print(len(layer.blocks))
    print("-"*10)

downsample (56, 56)
2
----------
downsample (28, 28)
2
----------
downsample (14, 14)
18
----------
2
----------


In [7]:
for i, layer in enumerate(model.layers):
    for block in layer.blocks:
        print(block.window_size)

7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7


In [37]:
vit = timm.create_model("vit_base_patch16_224")
print('the number of model parameters: {:,}'.format(sum([p.data.nelement() for p in vit.parameters()])))

the number of model parameters: 86,567,656


In [61]:
x = torch.Tensor([
    [[1,2,3,4],
     [6,7,8,9],
     [11,12,13,14],
     [16,17,18,19]]
])

print(x)
print("-"*10)
x1 = x[:, 0::2, 0::2]
print(x1)
print("-"*10)
x2 = x[:, 1::2, 0::2]
print(x2)
print("-"*10)
x3 = x[:, 0::2, 1::2]
print(x3)
print("-"*10)
x4 = x[:, 1::2, 1::2]
print(x4)
print("-"*10)



tensor([[[ 1.,  2.,  3.,  4.],
         [ 6.,  7.,  8.,  9.],
         [11., 12., 13., 14.],
         [16., 17., 18., 19.]]])
----------
tensor([[[ 1.,  3.],
         [11., 13.]]])
----------
tensor([[[ 6.,  8.],
         [16., 18.]]])
----------
tensor([[[ 2.,  4.],
         [12., 14.]]])
----------
tensor([[[ 7.,  9.],
         [17., 19.]]])
----------


In [ ]:
x = torch.randn((3,56,56,128))
